/** Textes propres à l'app (pas dans app/locales) : navigation, erreurs réseau,
 *  et l'espace acteurs — en français uniquement, comme /espace sur le web. */

export const S = {
  // Communs, par langue (les 4 langues du service ; mos/dyu retombent sur fr).
  common: {
    fr: { back: "Retour", next: "Continuer", cancel: "Annuler", retry: "Réessayer", network: "Pas de connexion. Vérifiez le réseau et réessayez.", server: "Le serveur n'a pas pu traiter la demande.", actors: "Espace acteurs", actors_sub: "Relais, point focal, action sociale, gestionnaire", copy: "Copier le code", copied: "Code copié", search: "Rechercher", changeLang: "Changer de langue", forget: "Effacer et revenir à l'accueil" },
    en: { back: "Back", next: "Continue", cancel: "Cancel", retry: "Retry", network: "No connection. Check the network and try again.", server: "The server could not process the request.", actors: "Staff area", actors_sub: "Relay, focal point, social services, case manager", copy: "Copy the code", copied: "Code copied", search: "Search", changeLang: "Change language", forget: "Clear and go back home" },
  } as Record<string, Record<string, string>>,

  roles: {
    RELAIS: "Relais communautaire", POINT_FOCAL: "Point focal VBG", ACTION_SOCIALE: "Action sociale", GESTIONNAIRE: "Gestionnaire de cas",
  } as Record<string, string>,

  statuses: { RECU: "Reçu", TRANSMIS: "Transmis", PRIS_EN_CHARGE: "Pris en charge", REGLE: "Réglé" } as Record<string, string>,

  actor: {
    login: "Connexion",
    login_intro: "Identifiants créés par l'administrateur. Réservé aux acteurs du circuit.",
    username: "Identifiant",
    password: "Mot de passe",
    bad_credentials: "Identifiant ou mot de passe incorrect.",
    too_many: "Trop de tentatives. Réessayez dans un quart d'heure.",
    inbox: "Signalements",
    all: "Tous",
    empty: "Rien pour le moment.",
    logout: "Déconnexion",
    newCase: "Saisir un cas reçu en personne",
    open: "Ouvrir",
    story: "Récit de la personne",
    summary: "Reformulation",
    legacy: "Ancien format de chiffrement : illisible tant que scripts/reencrypt.py n'a pas tourné sur le serveur.",
    unreadable: "Illisible (clé serveur absente).",
    history: "Historique",
    forward: "Transmettre",
    forwardTo: "À qui",
    anyone: "N'importe qui :",
    summaryLabel: "Reformulation (facultatif)",
    summaryRequired: "Reformulation (obligatoire)",
    relayRole: "Vous relayez, vous ne traitez pas : seuls l'action sociale et les gestionnaires de cas prennent en charge et changent le statut. Reformulez clairement la plainte, puis transmettez-la-leur.",
    summaryMissing: "Merci de reformuler clairement la plainte avant de la transmettre.",
    summaryHint: "Récit reformulé clairement pour la prise en charge : faits, date, lieu approximatif, besoin urgent. Toujours sans nom. Chiffré comme le récit.",
    noteLabel: "Mot pour le destinataire (facultatif, en clair)",
    notePlaceholder: "Ex. : urgent, mineure, déjà vue au CSPS",
    status: "Prise en charge",
    statusLabel: "Statut",
    partnerNote: "Message à la personne (facultatif)",
    partnerNoteHint: "La personne le lira avec son code de suivi. Aucun nom, aucun détail identifiant.",
    save: "Enregistrer",
    noStatusRight: "Seuls l'action sociale et les gestionnaires de cas prennent en charge et changent le statut.",
    pickRecipient: "Choisissez un destinataire.",
    forwarded: "Transmis.",
    alreadyForwarded: "Transmis à {to}. Le destinataire ne se choisit qu'une fois ; vous pouvez encore préciser votre reformulation.",
    summaryConcise: "Reformulation concise (obligatoire)",
    summaryConciseHint: "En quelques phrases claires : faits, quand, où (approximativement), besoin urgent. Toujours sans nom. Chiffré.",
    saveSummary: "Enregistrer la reformulation",
    propose: "Proposer une reformulation",
    proposeHint: "L'assistant propose un texte court et anonyme à partir du récit ; vous le relisez avant de transmettre.",
    proposed: "Proposition placée dans le champ. Relisez, corrigez, puis validez : vous restez l'auteur.",
    urgency: "Urgence estimée",
    toRemove: "À retirer ou vérifier",
    missing: "Il manque",
    aiUnavailable: "L'assistant de reformulation est indisponible pour le moment. Reformulez à la main.",
    summarySaved: "Reformulation enregistrée.",
    saved: "Enregistré.",
    with: "Chez",
    unassigned: "non attribué",
    newIntro: "Une personne est venue vous voir. Vous enregistrez son cas à sa place et le transmettez. Ne notez ni son nom, ni son numéro, ni son quartier. Donnez-lui le code de suivi affiché à la fin.",
    what: "Ce que la personne rapporte",
    whatHint: "Chiffré. Ses mots à elle, tels qu'elle les a dits.",
    createAndForward: "Enregistrer et transmettre",
    giveCode: "Remettez ce code à la personne. C'est le seul moyen pour elle de suivre son dossier.",
    by: "par",
    filed: "Signalement déposé",
    anonymous: "la personne (anonyme)",
    addressedTo: "adressé à",
    forwardedTo: "a transmis à",
    setStatus: "→",
    receivedVia: "reçu par",
    enteredBy: "saisi par",
  },
};

export const tc = (lang: string | null, key: string) => S.common[lang === "en" ? "en" : "fr"][key] ?? key;
